name: Build on Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04, ubuntu-22.04 ]

    runs-on: ${{ matrix.os }}
    name: "Build on ${{ matrix.os }}"

    env:
      sgl_REPO_DIR: ${{ github.workspace }}/sgl-repo
      sgl_DIR: ${{ github.workspace }}/sgl

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/checkout@v2
      with:
        repository: chrismile/sgl
        path: sgl-repo
        submodules: true

    - name: Install system packages
      shell: bash
      run: |
        sudo apt-get update
        distro_code_name=$(lsb_release -c | grep -oP "\:\s+\K\S+")
        if [ "$distro_code_name" = "jammy" ]; then
          # Fix for https://askubuntu.com/questions/1417403/can-not-install-libudev-dev-on-ubuntu-22-04/1417416#1417416
          sudo apt-get install aptitude
          sudo apt-get upgrade
          sudo apt-get --with-new-pkgs upgrade
          sudo aptitude full-upgrade -y
          sudo apt-get update
          sudo apt-get upgrade
        fi
        sudo apt-get install git cmake libglm-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
        libpng-dev libboost-filesystem-dev libtinyxml2-dev libarchive-dev libglew-dev libjsoncpp-dev libopenexr-dev

    - name: Install Vulkan SDK
      shell: bash
      run: |
        distro_code_name=$(lsb_release -c | grep -oP "\:\s+\K\S+")
        if ! curl -s -I "https://packages.lunarg.com/vulkan/lunarg-vulkan-${distro_code_name}.list" | grep "2 404" > /dev/null; then
          wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
          sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-${distro_code_name}.list \
          https://packages.lunarg.com/vulkan/lunarg-vulkan-${distro_code_name}.list
          sudo apt update
          sudo apt install vulkan-sdk shaderc
        else
          curl --silent --show-error --fail -O https://sdk.lunarg.com/sdk/download/latest/linux/vulkan-sdk.tar.gz
          mkdir -p VulkanSDK
          tar -xzf vulkan-sdk.tar.gz -C VulkanSDK
          # Fix pkgconfig file.
          shaderc_pkgconfig_file="VulkanSDK/$(ls VulkanSDK)/x86_64/lib/pkgconfig/shaderc.pc"
          prefix_path=$(realpath "VulkanSDK/$(ls VulkanSDK)/x86_64")
          sed -i '3s;.*;prefix=\"'$prefix_path'\";' "$shaderc_pkgconfig_file"
          sed -i '5s;.*;libdir=${prefix}/lib;' "$shaderc_pkgconfig_file"
          echo "PKG_CONFIG_PATH=\"$(realpath "VulkanSDK/$(ls VulkanSDK)/x86_64/lib/pkgconfig")\"" >> $GITHUB_ENV
        fi

    - name: Configure CMake (sgl)
      shell: bash
      run: |
        if [ "${{env.PKG_CONFIG_PATH}}" != "" ]; then
          VK_LAYER_PATH=""
          source "VulkanSDK/$(ls VulkanSDK)/setup-env.sh"
          export PKG_CONFIG_PATH="${{env.PKG_CONFIG_PATH}}"
        else
          export VULKAN_SDK="/usr"
        fi
        cmake ${{env.sgl_REPO_DIR}} -B ${{env.sgl_REPO_DIR}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.sgl_DIR}}

    - name: Build (sgl)
      run: cmake --build ${{env.sgl_REPO_DIR}}/build --config ${{env.BUILD_TYPE}} --parallel 4

    - name: Install (sgl)
      run: cmake --build ${{env.sgl_REPO_DIR}}/build --config ${{env.BUILD_TYPE}} --target install

    - name: Configure CMake (CloudRendering)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dsgl_DIR=${{env.sgl_DIR}}/lib/cmake/sgl

    - name: Build (CloudRendering)
      run: |
        if [ "${{env.PKG_CONFIG_PATH}}" != "" ]; then
          VK_LAYER_PATH=""
          source "VulkanSDK/$(ls VulkanSDK)/setup-env.sh"
          export PKG_CONFIG_PATH="${{env.PKG_CONFIG_PATH}}"
        fi
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 4
