name: Build on Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-18.04, ubuntu-20.04 ]

    runs-on: ${{ matrix.os }}
    name: "Build on ${{ matrix.os }}"

    env:
      sgl_REPO_DIR: ${{ github.workspace }}/sgl-repo
      sgl_DIR: ${{ github.workspace }}/sgl
      USE_EMBREE: true
      EMBREE_VERSION: "3.13.2"
      USE_OSPRAY: true
      OSPRAY_VERSION: "2.8.0"

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - uses: actions/checkout@v2
      with:
        repository: chrismile/sgl
        path: sgl-repo
        submodules: true

    - name: Install system packages
      run: |
        sudo apt-get update
        sudo apt-get install git cmake libglm-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev \
        libpng-dev libboost-filesystem-dev libtinyxml2-dev libarchive-dev libglew-dev libjsoncpp-dev libopenexr-dev

    - name: Install Vulkan SDK
      shell: bash
      run: |
        distro_code_name=$(lsb_release -c | grep -oP "\:\s+\K\S+")
        wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add -
        sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.3.204-${distro_code_name}.list \
        https://packages.lunarg.com/vulkan/1.3.204/lunarg-vulkan-1.3.204-${distro_code_name}.list
        sudo apt update
        sudo apt install vulkan-sdk shaderc

    - name: Download Embree
      if: env.USE_EMBREE
      shell: bash
      run: |
        wget "https://github.com/embree/embree/releases/download/v${{env.EMBREE_VERSION}}/embree-${{env.EMBREE_VERSION}}.x86_64.linux.tar.gz"
        tar -xvzf "embree-${{env.EMBREE_VERSION}}.x86_64.linux.tar.gz"

    - name: Download OSPRay
      if: env.USE_OSPRAY
      shell: bash
      run: |
        wget "https://github.com/ospray/OSPRay/releases/download/v${{env.OSPRAY_VERSION}}/ospray-${{env.OSPRAY_VERSION}}.x86_64.linux.tar.gz"
        tar -xvzf "ospray-${{env.OSPRAY_VERSION}}.x86_64.linux.tar.gz"

    - name: Configure CMake (sgl)
      run: cmake ${{env.sgl_REPO_DIR}} -B ${{env.sgl_REPO_DIR}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_INSTALL_PREFIX=${{env.sgl_DIR}}

    - name: Build (sgl)
      run: cmake --build ${{env.sgl_REPO_DIR}}/build --config ${{env.BUILD_TYPE}} --parallel 4

    - name: Install (sgl)
      run: cmake --build ${{env.sgl_REPO_DIR}}/build --config ${{env.BUILD_TYPE}} --target install

    - name: Configure CMake (CloudRendering)
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -Dsgl_DIR=${{env.sgl_DIR}}/lib/cmake/sgl -Dembree_DIR=${{github.workspace}}/embree-${{env.EMBREE_VERSION}}.x86_64.linux/lib/cmake/embree-${{env.EMBREE_VERSION}} -Dospray_DIR=${{github.workspace}}/ospray-${{env.OSPRAY_VERSION}}.x86_64.linux/lib/cmake/ospray-${{env.OSPRAY_VERSION}}

    - name: Build (CloudRendering)
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --parallel 4
